# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleCalculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleCalculator
  pod 'Expression', '~> 0.12'
  
  target 'SimpleCalculatorTests' do
      inherit! :complete
  end
  
end
